import { Scale, FileCheck, AlertTriangle, ShieldCheck, ArrowLeft, Gavel } from "lucide-react";
import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";

export default function TermsOfService() {
  const effectiveDate = "September 28, 2026";

  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl animate-in fade-in duration-500">
      {/* Back button */}
      <div className="mb-8">
        <Link to="/">
          <Button variant="ghost" size="sm" className="gap-2 text-zinc-400 hover:text-white">
            <ArrowLeft className="w-4 h-4" /> Back to Home
          </Button>
        </Link>
      </div>

      {/* Header */}
      <div className="space-y-4 mb-12 border-b border-border/40 pb-8">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-medium bg-primary/10 text-primary border border-primary/20">
          <Scale className="w-3.5 h-3.5" />
          <span>Platform Agreement</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-display font-bold text-foreground tracking-tight">
          Terms of Service
        </h1>
        <p className="text-muted-foreground text-sm sm:text-base leading-relaxed">
          Welcome to Nyastra AI. By accessing or using our platform, case search engines, document generators, or legal chatbots, you agree to be bound by these Terms of Service.
        </p>
        <p className="text-xs text-muted-foreground font-mono">
          Effective Date: {effectiveDate}
        </p>
      </div>

      {/* Crucial Legal Disclaimer Banner */}
      <div className="p-5 rounded-xl border border-amber-500/30 bg-amber-500/5 backdrop-blur-sm mb-12 space-y-2">
        <div className="flex items-center gap-2 text-amber-400 font-semibold text-sm">
          <AlertTriangle className="w-5 h-5 shrink-0" />
          <span>Notice to Advocates & Legal Practitioners</span>
        </div>
        <p className="text-xs text-muted-foreground leading-relaxed pl-7">
          Nyastra AI is an advanced AI-powered research and drafting assistant built to augment, not replace, professional human judgment. The outputs generated by our AI models (including citations, case summaries, draft petitions, and statutory references) do not constitute formal legal advice. Practicing advocates are solely responsible for verifying citations, cross-checking precedents with official gazettes/court records, and ensuring compliance with the Bar Council of India rules prior to filing or advising clients.
        </p>
      </div>

      {/* Terms Content */}
      <div className="space-y-10 text-foreground/90 text-sm leading-relaxed">
        {/* Section 1 */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
            <span className="text-primary font-mono text-xs px-2 py-0.5 rounded bg-primary/10">01</span>
            Scope of Service & Eligibility
          </h2>
          <p className="text-muted-foreground">
            Nyastra AI provides a suite of legal intelligence tools, including neural judgment search, case fact matching, AI-assisted legal drafting, and interactive statutory question answering. The service is available to advocates, law firms, legal educators, corporate legal counsels, and law students in good standing.
          </p>
        </section>

        {/* Section 2 */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
            <span className="text-primary font-mono text-xs px-2 py-0.5 rounded bg-primary/10">02</span>
            Intellectual Property & Work Product Ownership
          </h2>
          <div className="space-y-2 text-muted-foreground">
            <p>
              <strong>Your Work Product:</strong> You retain 100% full legal ownership, copyright, and title to all case facts, bespoke inputs, and completed legal drafts (plainting, writ petitions, notices) created through Nyastra AI.
            </p>
            <p>
              <strong>Platform Rights:</strong> All proprietary software, database schemas, scoring algorithms, and brand assets of Nyastra AI remain the exclusive intellectual property of Nyastra AI and its founder.
            </p>
          </div>
        </section>

        {/* Section 3 */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
            <span className="text-primary font-mono text-xs px-2 py-0.5 rounded bg-primary/10">03</span>
            Acceptable Use Policy
          </h2>
          <p className="text-muted-foreground">
            When utilizing Nyastra AI, you agree not to:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-muted-foreground text-xs sm:text-sm">
            <li>Submit classified, national security-restricted, or seal-order judicial documents prohibited by court order.</li>
            <li>Attempt to reverse-engineer, decompile, or extract the underlying model parameters and proprietary prompt chains.</li>
            <li>Conduct denial-of-service, automated scraping, or rate-limit circumvention against our API endpoints.</li>
            <li>Use the platform to generate frivolous, harassing, or knowingly fraudulent legal proceedings.</li>
          </ul>
        </section>

        {/* Section 4 */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
            <span className="text-primary font-mono text-xs px-2 py-0.5 rounded bg-primary/10">04</span>
            Third-Party Services & Public Judgments
          </h2>
          <p className="text-muted-foreground">
            Judicial records, headnotes, and public case texts are retrieved in real-time from open legal repositories, public high court websites, and Indian Kanoon. Nyastra AI does not alter official court records and holds no liability for typographical or reporting inaccuracies present in source repositories.
          </p>
        </section>

        {/* Section 5 */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
            <span className="text-primary font-mono text-xs px-2 py-0.5 rounded bg-primary/10">05</span>
            Limitation of Liability
          </h2>
          <p className="text-muted-foreground">
            To the maximum extent permitted by applicable Indian laws, Nyastra AI, its developers, and affiliates shall not be liable for any direct, indirect, incidental, punitive, or consequential damages resulting from lost case outcomes, procedural delays, citation misattributions, or judicial interpretations derived from AI-generated outputs.
          </p>
        </section>

        {/* Section 6 */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
            <span className="text-primary font-mono text-xs px-2 py-0.5 rounded bg-primary/10">06</span>
            Governing Law & Jurisdiction
          </h2>
          <p className="text-muted-foreground">
            These Terms shall be governed by and construed in accordance with the substantive laws of the Republic of India. Any dispute, claim, or controversy arising out of or relating to these Terms or the use of Nyastra AI shall be subject to the exclusive jurisdiction of the competent courts in New Delhi, India.
          </p>
        </section>

        {/* Section 7 */}
        <section className="space-y-3">
          <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
            <span className="text-primary font-mono text-xs px-2 py-0.5 rounded bg-primary/10">07</span>
            Modifications & Inquiries
          </h2>
          <p className="text-muted-foreground">
            We reserve the right to revise these Terms periodically. Continued usage following amendments constitutes affirmative acceptance. For any legal inquiries regarding these terms, reach us at <a href="mailto:support@nyastra.ai" className="text-primary underline">support@nyastra.ai</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
